### ISSUE TITLE
Add React Router

### ISSUE THREAD

**Issue by lilywuyanru** [henryngann/CoLab#17]
Add React Router
- we need to some refactoring for VideoChat.js

**Comment by matthewwong525** [comment]
Have a toggle between youtube room and normal room while video chatting. Delete workflow for creating youtube room.

**Comment by lilywuyanru** [comment]
I think we can introduce React `Context` as well, instead of passing in `RoomName`, `RoomState` etc through props from Home to Room, we can have those values in a Context. Another reason is that  with React Router, we probably have to use query strings to store those values, it's not very scalable with the amount of data we want to pass into each component 

The two components can be more independent of each other, and the Router only has to worry about which component to render and not about the props.
